<a href="https://colab.research.google.com/github/riddhaxxx/Sales-Data-Analysis-2/blob/main/E_Commerce_Sales_Analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import sqlite3

In [2]:
from google.colab import files
uploaded = files.upload()

Saving Amazon Sale Report.csv to Amazon Sale Report (1).csv

In [3]:
df = pd.read_csv("Amazon Sale Report.csv")
df.head()

/tmp/ipykernel_18704/3949281228.py:1: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Amazon Sale Report.csv")

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [4]:
df.columns = df.columns.str.strip()  # removes extra spaces
df.columns = df.columns.str.replace(" ", "_")
df.columns

Index(['index', 'Order_ID', 'Date', 'Status', 'Fulfilment', 'Sales_Channel',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier_Status', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids',
       'B2B', 'fulfilled-by', 'Unnamed:_22'],
      dtype='object')

In [5]:
conn = sqlite3.connect("Sales.db")
df.to_sql("Sales", conn, if_exists="replace",index=False)

128975

In [6]:
query = "SELECT SUM(Amount) AS Total_Sales FROM Sales"
pd.read_sql(query, conn)

   Total_Sales
0   78592678.3

In [7]:
query = """
SELECT Category, SUM(Amount) AS total_sales
FROM Sales
GROUP BY Category
ORDER BY total_sales DESC
"""
pd.read_sql(query, conn)

        Category  total_sales
0            Set  39204124.03
1          kurta  21299546.70
2  Western Dress  11216072.69
3            Top   5347792.30
4   Ethnic Dress    791217.66
5         Blouse    458408.18
6         Bottom    150667.98
7          Saree    123933.76
8        Dupatta       915.00

In [8]:
query = """
SELECT Sales_Channel, SUM(Amount) AS total_sales
FROM Sales
GROUP BY Sales_Channel
ORDER BY total_sales DESC
"""
pd.read_sql(query, conn)

  Sales_Channel  total_sales
0     Amazon.in   78592678.3
1    Non-Amazon          NaN

In [11]:
pd.read_sql("SELECT * FROM sales LIMIT 1", conn)

,index,Order_ID,Date,Status,Fulfilment,Sales_Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed:_22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,None,0,Easy Ship,None

In [15]:
query = """
SELECT "ship-city", SUM(Amount) AS total_sales
FROM sales
GROUP BY "ship-city"
ORDER BY total_sales DESC
LIMIT 5
"""
pd.read_sql(query, conn)

   ship-city  total_sales
0  BENGALURU   6849664.99
1  HYDERABAD   4946032.82
2     MUMBAI   3704461.80
3  NEW DELHI   3613874.78
4    CHENNAI   3098745.74

In [14]:
query = """
SELECT strftime('%m', Date) AS month,
       SUM(Amount) AS total_sales
FROM sales
GROUP BY month
ORDER BY month
"""
pd.read_sql(query, conn)

  month  total_sales
0  None   78592678.3